---

- name: "Install of apache"
  apt:
    name: "apache2"
    state: present
  when: 
    - ansible_distribution == "Ubuntu"
    - ansible_distribution_version == "18.04"

- name: "apache start config"
  service:
    name: apache2
    state: started
    enabled: true
  when:
    - ansible_distribution == "Ubuntu"
    - ansible_distribution_version == "18.04"
 
- name: "check apache version"
  command: apachectl -v
  register: apacheversion

- name: "show apacheversion"
  debug:
    msg: "apache version is: {{ apacheversion }}"

- name: "copy apache2.conf"
  template:
    src: roles/apache/template/apache2.conf
    dest: etc/apache2/apache.conf
